#!/usr/bin/env bash

#################### SOURCES / TARGETS / PATHS #################### 

PACMAN_PACKAGES_PATH="./packages/pacman.txt"
PARU_PACKAGES_PATH="./packages/pacman.txt"
SERVICES_PATH="./services.txt"
VSCODE_EXTENSIONS_PATH="./configure/code-oss/extensions.txt"
LOGGFILE_PATH="./$(date +%Hh%Mm)_install.log"

# configs
CONFIG_SOURCE_PATH="$(pwd)/dotfiles/.config"
CONFIG_TARGET_PATH="${HOME}/.config"
APPLICATIONS_SOURCE_PATH="$(pwd)/dotfiles/.local/share/applications"
APPLICATIONS_TARGET_PATH="${HOME}/.local/share/applications"
HOME_SOURCE_PATH="$(pwd)/dotfiles"
HOME_TARGET_PATH="$HOME"
VSCODE_SOURCE_PATH="$(pwd)/configure/code-oss/User/settings.json"
VSCODE_TARGET_PATH="${HOME}/.config/Code - OSS/User"
KEYD_SOURCE_PATH="${HOME}/.config/keyd/default.conf"
KEYD_TARGET_PATH="/etc/keyd/"

# I like to keep the directory structure as intended once deployed,
# but that means we can end up messing with configs that are
# handled by some other metod and thus clash. Therefore,
# I have added a way to ignore configs that are independently handled.
HOME_IGNORE_PATHS=("$CONFIG_SOURCE_PATH" "$(pwd)/dotfiles/.local")

# neovim tree-sitter parser paths
NVIM_PARSERS_PATH="${HOME}/.config/nvim/parser"
NVIM_PARSERS_DIR="${HOME}/.config/nvim/parser-repos"

# neovim tree-sitter query paths
NVIM_TREE_SITTER_DOWNLOAD_PATH="${HOME}/nvim-treesitter"
NVIM_TREE_SITTER_QUERIES_SOURCE_PATH="${NVIM_TREE_SITTER_DOWNLOAD_PATH}/runtime/queries"
NVIM_TREE_SITTER_QUERIES_TARGET_PATH="${HOME}/.config/nvim/queries"

# misc
PING_TEST_URL="archlinux.org"
DIST_ID="arch"
BACKUP_EXT=".bak"
CUR_LINUX_VERSION="7.0.8"
DATE_OF_WRITING="2026.05.21"
THEME="Papirus"

# urls
GITHUB_URL_BASE="https://github.com"
TS_URL="${GITHUB_URL_BASE}/nvim-treesitter/nvim-treesitter"
TS_PARSERS_URL_BASE="${GITHUB_URL_BASE}/tree-sitter/tree-sitter-"
TS_BASH_URL="${TS_PARSERS_URL_BASE}bash"
TS_REGEX_URL="${TS_PARSERS_URL_BASE}regex"
TS_HTML_URL="${TS_PARSERS_URL_BASE}html"
TS_CSS_URL="${TS_PARSERS_URL_BASE}css"
TS_JAVASCRIPT_URL="${TS_PARSERS_URL_BASE}javascript"
TS_TYPESCRIPT_URL="${TS_PARSERS_URL_BASE}typescript"
TS_PYTHON_URL="${TS_PARSERS_URL_BASE}python"
TS_SVELTE_URL="${GITHUB_URL_BASE}/tree-sitter-grammars/tree-sitter-bash"
TS_PARSERS_URLS=(
	TS_BASH_URL
	TS_REGEX_URL
	TS_HTML_URL
	TS_CSS_URL
	TS_JAVASCRIPT_URL
	TS_TYPESCRIPT_URL
	TS_PYTHON_URL
	TS_SVELTE_URL
)
PARU_GIT_URL="https://aur.archlinux.org/paru.git"

#################### LOGGING #################### 

R="\e[m"
BOLD="\e[1m"
ITALIC="\e[3m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"

OK="[${BOLD}${GREEN}+${R}]"
INFO="[${BOLD}>${R}]"
WARNING="[${BOLD}${YELLOW}-${R}]"
ERROR="[${BOLD}${RED}!${R}]"

function write_to_logfile() { echo "[$(date +%T)] $1" >> "$LOGGFILE_PATH"; }
function s() { echo "--------------------------------------------------------------------------------"; }
function separator() { echo $(s); echo "[$(date +%T)] $(s)" >> "$LOGGFILE_PATH"; }
function logging_info() { echo -e "$INFO $1"; write_to_logfile "[>] $1"; }
function logging_ok() { echo -e "$OK $1"; write_to_logfile "[+] $1"; }
function logging_warning() { echo -e "$WARNING $1"; write_to_logfile "[-] $1"; }

function logging_error() {
	echo -e "$ERROR $1"
	write_to_logfile "[!] $1"
	# an `exit 1` usually happens after here, notify about the logfile
	echo "See ${LOGGFILE_PATH} for more information"
}

#################### META STUFF #################### 

function yes_no() {
	local q="${1:-Continue?}"
	read -r -p "$q [y/N]: " answer
	write_to_logfile "${q} [y/N]: ${answer}"
	[[ $answer =~ ^[Yy]$ ]]
}

function check_create_dir() {
	local path=$1
	if [[ ! -e "$path" ]]; then
		logging_info "Directory [${path}] not found. Creating..."
		if ! mkdir -p -- "$path"; then
			logging_error "Error occurred while creating direcory [${path}]! Cancelling..."
			exit 1
		fi
	fi
}

#################### STARTUP ####################

echo "
______________________________________________________________________
|
| Last updated ${DATE_OF_WRITING}
| 
| This script is written to work exclusevly with my (gobbls)
| computer — a Lenovo X1 Carbon Gen. 10 with Arch Linux (${CUR_LINUX_VERSION})
| — in order to fully recreate my current setup and preferences.
| There is no guarantee that it will work with your system.
| 
| This script is intended to be ran immediately after a fresh
| Arch install, but needs to meet the following preconditions:
|  - WAN connection
|  - [sudo] installed with user added to group
| 
| Preexisting files in these directories will be backed up
| before symlinking files with the same names:
|  - [~/*]
|  - [~/.config/*]
|  - [~/.local/share/applications/*]
| 
| Intentionaly excluded configs / setups:
|  - FStab
|  - AppImage downlaods and unzipping
|  - [~/] directories for Thunar bookmarks
|  - Virsh network service ($ virsh net-start default)
|_____________________________________________________________________
"

logging_info "Bootstrapping Gobbls' dots..."
separator

#################### GET SUDO ####################

# avoid waiting for prompt input on every sudo action.
# NB: doesn't work with paru build, can't preemptively use `sudo` for `makepkg -i`.
read -sp "Type your (sudo) password: " pass

echo ""
write_to_logfile ""

# test the password, might pass due to correct password still being
# valid from earlier don't know how to correct that.
if ! echo "$pass" | sudo -S ls > /dev/null 2>&1; then
	logging_warning "Incorrect password. Cancelling..."
	exit 0
fi

#################### SYSTEM CHECKS ####################

logging_info "Checking if [sudo] is accessible..."
if ! type -p sudo > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_error "[sudo] not available, but is required to install packages! Cancelling..."
	exit 1
fi
logging_ok "[sudo] is accessible"

logging_info "Checking for WAN connection (pinging ${PING_TEST_URL})..."
if ! ping -c 2 -W 3 -q -- "$PING_TEST_URL" > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_error "${PING_TEST_URL} not reachable! Internet connection is required. Cancelling..."
	exit 1
fi
logging_ok "Verified connection"

dist="Arch Linux"

path="/etc/os-release"
logging_info "Checking if system is ${dist}..."
if [[ ! -f "$path" ]]; then
	logging_error "Unable to locate [${path}]: Not able to check if distro type is ${dist}. Cancelling..."
	exit 1
fi
source "$path"

if [[ "$ID" == "$DIST_ID" ]]; then
    logging_ok "System is ${dist}"
elif [[ "$ID_LIKE" == *"$DIST_ID"* ]]; then
    logging_warning "System is *based* on ${dist}, this script is not tested on such systems"
	if ! yes_no "Continue?"; then
		logging_info "Cancelling..."
		exit 0
	fi
else
	logging_error "This installation script is not made for systems other than ${dist}! Cancelling..."
	exit 1
fi

separator

#################### DEPLOY DOTFILES #################### 

function backup_conf() {
	local path=$1
	local bak_num=1
	local bak_path="${path}${BACKUP_EXT}"
	while [[ -e "$bak_path" ]]; do
		bak_num=$((bak_num + 1))
		bak_path="${path}${BACKUP_EXT}${bak_num}"
	done
	if ! mv -- "$path" "$bak_path"; then
		logging_error "Error occurred while moving [${path}] to [${bak_path}]! Cancelling..."
		exit 1
	fi
	logging_ok "[${path}] backed up to [${bak_path}]"
}

function create_symlink() {
	local source_path=$1
	local target_path=$2
	if ! ln -s -- "$source_path" "$target_path"; then
		logging_error "Error occurred while symlinking [${target_path}] -> [${source_path}]! Cancelling..."
		exit 1
	fi
	logging_ok "Symlink created: [${target_path}] -> [${source_path}]"
}

function item_in_list() {
	local item=$1
	shift
	local list=("$@")
	for i in "${list[@]}"; do
		[[ "$i" == "$item" ]] && return 0
	done
	return 1
}

function deploy_dir() {
	local conf_source=$1 conf_target=$2
	shift 2
	local conf_ignore=("$@")
	logging_info "Deploying from [${conf_source}/]..."
	check_create_dir "$conf_target"
	for conf in "$conf_source"/* "$conf_source"/.*; do
		[[ -e "$conf" ]] || continue # skip the [$conf_source/*] literals if there is no match
		local conf_name=${conf##*/}
		if item_in_list "$conf" "${conf_ignore[@]}"; then continue; fi
		local target_conf_path="${conf_target}/${conf_name}"
		if [[ -e "$target_conf_path" ]]; then
			logging_warning "[${conf_name}] already exists in [${conf_target}/]! Creating backup before linking..."
			backup_conf "$target_conf_path"
		fi
		create_symlink "$conf" "$target_conf_path"
	done
}

#			source_path					target_path					ignore_item
deploy_dir 	"$CONFIG_SOURCE_PATH"		"$CONFIG_TARGET_PATH"	
deploy_dir 	"$APPLICATIONS_SOURCE_PATH"	"$APPLICATIONS_TARGET_PATH"
deploy_dir 	"$HOME_SOURCE_PATH"			"$HOME_TARGET_PATH"			$HOME_IGNORE_PATHS	

separator

#################### PACMAN INSTALL #################### 

logging_info "Installing packages with [pacman]..."
logging_info "Synchronizing packages (this might take some time)..."
if ! echo "$pass" | sudo -S pacman -Sy > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_error "Error occurred while synching packages! Cancelling..."
	exit 1
fi

pacman_packages_len=$(wc -l "$PACMAN_PACKAGES_PATH" | awk '{print $1}')
logging_info "Installing [${pacman_packages_len}] packages (this might take some time)..."
mapfile -t pacman_packages < "$PACMAN_PACKAGES_PATH"
if ! echo "$pass" | sudo -S pacman -S --needed --noconfirm -- "${pacman_packages[@]}" > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_error "Error occurred while installing [pacman] packages! Cancelling..."
	exit 1
fi
logging_ok "Successfully installed [pacman] packages"

separator

#################### RUSTUP INSTALL ####################

logging_info "Installing [rust] with [rustup]..."
if ! type -p rustup > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_warning "[rustup] should have been installed before, but was not found! Cancelling..."
	exit 1
fi

if ! rustup default stable > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_error "Error occurred while installing [rust]! Cancelling..."
	exit 1
fi
logging_ok "[rust] installed successfully"

separator

#################### INSTALL PARU ####################

function cleanup() {
	cd - > /dev/null
	rm -rf "$temp_dir"
}

logging_info "Checking if [paru] is installed..."
if ! type -p paru > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_info "[paru] not found. Installing..."
	temp_dir=$(mktemp -d)
	if ! git clone --depth=1 -- "$PARU_GIT_URL" "$temp_dir" > /dev/null 2>> "$LOGGFILE_PATH"; then
		logging_error "Failed to clone the [paru] repo! Cleaning up then cancelling..."
		rmdir "$temp_dir"
		exit 1
	fi
	cd "$temp_dir"
	logging_info "Building and installing [paru] package with [makepkg] (this might take some time)..."
	if ! makepkg -sir 2>> "$LOGGFILE_PATH"; then
		logging_error "Error occurred while installing [paru]! Cleaning up then cancelling..."
		cleanup
		exit 1
	fi
	logging_info "Build complete. Cleaning up..."
	cleanup
else
	logging_info "Paru is already installed. Skipping..."
fi

separator

#################### PARU INSTALL ####################

paru_packages_len=$(wc -l packages/paru.txt | awk '{print $1}')
logging_info "Synching and Installing [${paru_packages_len}] packages (this might take some time)..."
mapfile -t paru_packages < "$PARU_PACKAGES_PATH"
if ! echo "$pass" | sudo -S paru -S --needed --noconfirm -- "${paru_packages[@]}" > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_error "Error occurred when installing [paru] packages! Cancelling..."
	exit 1
fi

separator

#################### ENABLE SERVICES ####################

logging_info "Enabling services..."
mapfile -t services < "$SERVICES_PATH"
if ! echo "$pass" | sudo -S systemctl enable --now "${services[@]}" > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_warning "Error occurred while enabling service(s)! Skipping..."
fi

separator

#################### VSCODE ####################

logging_info "Installing [code-oss] extensions..."
if ! cat "${VSCODE_EXTENSIONS_PATH}" | xargs -n 1 code --install-extension > /dev/null 2>> "$LOGGFILE_PATH"; then
	logging_warning "Error occurred while installing [code-oss] extension(s)! Skipping..."
else
	logging_ok "Successfully installed [code-oss] extensions"
fi

logging_info "Linking [code-oss] settings file..."
check_create_dir "$VSCODE_TARGET_PATH"
if ! ln -s -- "$VSCODE_SOURCE_PATH" "$VSCODE_TARGET_PATH" 2>> "$LOGGFILE_PATH"; then
	logging_warning "Failed to link [code-oss] settings file! Skipping..."
else
	logging_ok "Linked [code-oss] settings file"
fi

separator

#################### ADD USER TO LIBVIRT GROUP ####################

# For permission to start up kvm/qemu.
logging_info "Adding [${USER}] to [libvirt] group..."
if ! echo "$pass" | sudo -S usermod -aG libvirt $USER 2>> "$LOGGFILE_PATH"; then
	logging_warning "Unable to add user to group! Skipping..."
else
	logging_ok "User added to group"
fi

separator

#################### SYMLINK KEYD CONFIG ####################

logging_info "Symlinking [keyd] config..."
if ! echo "$pass" | sudo -S ln -s -- "$KEYD_SOURCE_PATH" "$KEYD_TARGET_PATH"; then
	logging_warning "Error occurred while symlinking [keyd] config! Skipping..."
else
	logging_ok "[keyd] config symlinked"
fi

separator

#################### SET THEME ####################

# Arch relies mostly on [org.gnome] for themes, instead of GTK / QT, and needs to be set
logging_info "Setting icon theme to [${THEME}]..."
if ! gsettings set org.gnome.desktop.interface icon-theme "$THEME" 2>> "$LOGGFILE_PATH"; then
	logging_warning "Error occurred while setting the icon theme! Skipping..."
else
	logging_ok "[${THEME}] icon theme set successfully"
fi

separator

#################### NEOVIM TREE-SITTER QUERY SETUP ####################

function clone_ts_repo() {
	logging_info "Cloning [nvim-treesitter] repo..."
	if ! git clone --depth=1 -- "$TS_URL" "$NVIM_TREE_SITTER_DOWNLOAD_PATH" > /dev/null 2>> "$LOGGFILE_PATH"; then
		logging_warning "Failed to clone [nvim-treesitter]! Skipping..."
		return 1
	fi
	return 0
}

function copy_ts_queries() {
	logging_info "Copying [nvim-treesitter] queries into [neovim] config..."
	check_create_dir "$NVIM_TREE_SITTER_QUERIES_TARGET_PATH"
	if ! cp -r -- "$NVIM_TREE_SITTER_QUERIES_SOURCE_PATH" "$NVIM_TREE_SITTER_QUERIES_TARGET_PATH" 2>> "$LOGGFILE_PATH"; then
		logging_warning "Failed to copy from [${NVIM_TREE_SITTER_QUERIES_SOURCE_PATH}] to [${NVIM_TREE_SITTER_QUERIES_TARGET_PATH}]! Skipping..."
		return 1
	fi
	return 0
}

function delete_ts_repo() {
	logging_info "Deleting [nvim-treesitter] repo..."
	if ! rm -rf -- "$NVIM_TREE_SITTER_DOWNLOAD_PATH" 2>> "$LOGGFILE_PATH"; then
		logging_warning "Not able to delete [${NVIM_TREE_SITTER_DOWNLOAD_PATH}]! Skipping..."
		return 1
	fi
	return 0
}

clone_ts_repo && copy_ts_queries && delete_ts_repo

separator

#################### NEOVIM TREE-SITTER PARSERS SETUP ####################

# WIP
echo "NB!: Still need to set up the tree-sitter parsers"
separator

#################### END ####################

echo "Done!"
