#!/usr/bin/env bash

# cmake \
# discord \
# libadwaita \
# libreoffice-fresh \
# obsidian \
# otf-font-awesome \
# qbittorrent \
# qt5-wayland \
# qt6-base \
# qt6-wayland \
# rustup \
# xdg-desktop-portal-wlr \
# file-roller \
# luarocks \
# lua-language-server \
# svelte-language-server \
# typescript-language-server \

sudo pacman -S --needed \
	7zip \
	bat \
	blueman \
	bluez \
	brightnessctl \
	btop \
	celluloid \
	chromium \
	curl \
	fastfetch \
	fd \
	ffmpeg \
	ffmpegthumbnailer \
	firefox \
	foot \
	fzf \
	gcc \
	gimp \
	git \
	gnome-themes-extra \
	grep \
	grim \
	gvfs \
	gvfs-mtp \
	htop \
	lazygit \
	loupe \
	man-db \
	mpv \
	neovim \
	network-manager-applet \
	networkmanager \
	nodejs \
	noto-fonts \
	noto-fonts-cjk \
	noto-fonts-emoji \
	noto-fonts-extra \
	npm \
	nwg-look \
	papirus-icon-theme \
	pavucontrol \
	python \
	python-pip \
	ripgrep \
	slurp \
	sudo \
	sway \
	swaybg \
	swayidle \
	swaylock \
	swaync \
	thunar-archive-plugin \
	thunar-volman \
	tmux \
	ttf-0xproto-nerd \
	ttf-firacode-nerd \
	ttf-hack-nerd \
	ttf-jetbrains-mono-nerd \
	ttf-noto-nerd \
	ttf-sourcecodepro-nerd \
	tumbler \
	unrar \
	unzip \
	vi \
	waybar \
	webp-pixbuf-loader \
	wget \
	wireplumber \
	wofi \
	xarchiver \
	xorg-xwayland \
	yazi \
	yt-dlp \
