#!/usr/bin/env bash

#################### META STUFF #################### 

R="\e[m"
BOLD="\e[1m"
ITALIC="\e[3m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"

OK="[${BOLD}${GREEN}+${R}]"
INFO="[${BOLD}>${R}]"
WARNING="[${BOLD}${YELLOW}-${R}]"
ERROR="[${BOLD}${RED}!${R}]"

logging_info() { echo -e "$INFO $1"; }
logging_ok() { echo -e "$OK $1"; }
logging_warning() { echo -e "$WARNING $1"; }
logging_error() { echo -e "$ERROR $1"; }

separator() { echo "--------------------------------------------------------------------------------"; }

yes_no() {
	local q="${1:-Continue?}"
	read -r -p "$q [y/N]: " answer
	[[ $answer =~ ^[Yy]$ ]]
}

check_create_dir() {
	local path=$1
	if [[ ! -e "$path" ]]; then
		logging_info "Directory [${path}] not found. Creating..."
		if ! mkdir -p -- "$path"; then
			logging_error "Error occurred while creating direcory [${path}]! Cancelling..."
			exit 1
		fi
	fi
}

#################### STARTUP ####################

logging_info "Bootstrapping Gobbls' dots..."

separator

#################### GET SUDO ####################

# avoid waiting for prompt input on every sudo action
read -sp "Type your (sudo) password: " pass

echo ""

# test the password, might pass due to correct password still being valid from earlier.
if ! echo "$pass" | sudo -S ls > /dev/null 2>&1; then
	logging_error "Incorrect password. Cancelling..."
	exit 0
fi

#################### SYSTEM CHECKS ####################

logging_info "Checking if [sudo] is accessible..."
if ! type -p sudo > /dev/null 2>&1; then
	logging_error "[sudo] not available, but is required to install packages! Cancelling..."
	exit 1
fi
logging_ok "[sudo] is accessible"

dest="archlinux.org"
logging_info "Checking for WAN connection (pinging ${dest})..."
if ! ping -c 2 -W 3 -q "$dest" > /dev/null 2>&1; then
	logging_error "${dest} not reachable! Internet connection is required. Cancelling..."
	exit 1
fi
logging_ok "Verified connection"

dist="Arch Linux"
path="/etc/os-release"
logging_info "Checking if system is ${dist}..."
if [[ ! -f "$path" ]]; then
	logging_error "Unable to locate [${path}]: Not able to check if distro type is ${dist}. Cancelling..."
	exit 1
fi
source "$path"

if [[ "$ID" == "arch" ]]; then
    logging_ok "System is ${dist}"
elif [[ "$ID_LIKE" == *"arch"* ]]; then
    logging_warning "System is *based* on ${dist}, this script is not tested on such systems"
	if ! yes_no "Continue?"; then
		logging_info "Cancelling..."
		exit 0
	fi
else
	logging_error "This installation script is not made for systems other than ${dist}! Cancelling..."
	exit 1
fi

separator

#################### DEPLOY DOTFILES #################### 

function backup_conf() {
	local path=$1
	local bak_num=1
	local bak_path="${path}.bak"
	while [[ -e "$bak_path" ]]; do
		bak_num=$((bak_num + 1))
		bak_path="${path}.bak${bak_num}"
	done
	if ! mv -- "$path" "$bak_path"; then
		logging_error "Error occurred while moving [${path}] to [${bak_path}]! Cancelling..."
		exit 1
	fi
	logging_ok "[${path}] backed up to [${bak_path}]"
}

function create_symlink() {
	local source_path=$1
	local target_path=$2
	if ! ln -s -- "$source_path" "$target_path"; then
		logging_error "Error occurred while symlinking [${target_path}] -> [${source_path}]! Cancelling..."
		exit 1
	fi
	logging_ok "Symlink created: [${target_conf_path}] -> [${source_path}]"
}

function item_in_list() {
	local item=$1
	shift
	local list=("$@")
	for i in "${list[@]}"; do
		[[ "$i" == "$item" ]] && return 0
	done
	return 1
}

function deploy_dir() {
	local conf_source=$1 conf_target=$2
	shift 2
	local conf_ignore=("$@")
	logging_info "Deploying from [${conf_source}/]..."
	check_create_dir "$conf_target"
	for conf in "$conf_source"/* "$conf_source"/.*; do
		[[ -e "$conf" ]] || continue # skip the [$conf_source/*] literals if there is no match
		local conf_name=${conf##*/}
		if item_in_list "$conf" "${conf_ignore[@]}"; then continue; fi
		local target_conf_path="${conf_target}/${conf_name}"
		if [[ -e "$target_conf_path" ]]; then
			logging_warning "[${conf_name}] already exists in [${conf_target}/]! Creating backup before linking..."
			backup_conf "$target_conf_path"
		fi
		create_symlink "$conf" "$target_conf_path"
	done
}

#			source_path									target_path							ignore_item
deploy_dir 	"$(pwd)/dotfiles/.config" 					"${HOME}/.config"
deploy_dir 	"$(pwd)/dotfiles/.local/share/applications"	"${HOME}/.local/share/applications"
deploy_dir 	"$(pwd)/dotfiles" 							"$HOME" 							"$(pwd)/dotfiles/.config" "$(pwd)/dotfiles/.local"

separator

#################### PACMAN INSTALL #################### 

logging_info "Installing packages with [pacman]..."
pacman_packages_len=$(wc -l packages/pacman.txt | awk '{print $1}')
logging_info "Synchronizing packages (this might take some time)..."
if ! echo "$pass" | sudo -S pacman -Sy > /dev/null 2>&1; then
	logging_error "Error occurred while synching packages! Cancelling..."
	exit 1
fi

logging_info "Installing [${pacman_packages_len}] packages (this might take some time)..."
mapfile -t pacman_packages < packages/pacman.txt
if ! echo "$pass" | sudo -S pacman -S --needed --noconfirm "${pacman_packages[@]}" > /dev/null 2>&1; then
	logging_error "Error occurred while installing [pacman] packages! Cancelling..."
	exit 1
fi
logging_ok "Successfully installed [pacman] packages"

separator

#################### RUSTUP INSTALL ####################

logging_info "Installing [rust] with [rustup]..."
if ! type -p rustup > /dev/null 2>&1; then
	logging_warning "[rustup] should have been installed before, but was not found! Cancelling..."
	exit 1
fi

if ! rustup default stable > /dev/null 2>&1; then
	logging_error "Error occurred while installing [rust]! Cancelling..."
	exit 1
fi
logging_ok "[rust] installed successfully"

separator

#################### INSTALL PARU ####################

function cleanup() {
	cd - > /dev/null
	rm -rf "$temp_dir"
}

logging_info "Checking if [paru] is installed..."
paru_git="https://aur.archlinux.org/paru.git"
if ! type -p paru > /dev/null 2>&1; then
	logging_info "[paru] not found. Installing..."
	temp_dir=$(mktemp -d)
	logging_info "Temporary directory [${temp_dir}] created"
	logging_info "Cloning [paru] repo..."
	if ! git clone "$paru_git" "$temp_dir" > /dev/null 2>&1; then
		logging_error "Failed to clone the [paru] repo! Cleaning up then cancelling..."
		rmdir "$temp_dir"
		exit 1
	fi
	cd "$temp_dir"
	logging_info "Building [paru] with [makepkg]..."
	if ! makepkg -s --noconfirm > /dev/null 2>&1; then
		logging_error "Error occurred while building [paru]! Cleaning up then cancelling..."
		cleanup
		exit 1
	fi
	logging_info "Installing [paru] package with [makepkg]..."
	if ! echo "$pass" | sudo -S makepkg -i --noconfirm > /dev/null 2>&1; then
		logging_error "Error occurred while installing [paru]! Cleaning up then cancelling..."
		cleanup
		exit 1
	fi
	logging_info "Build complete. Cleaning up..."
	cleanup
else
	logging_info "Paru is already installed. Skipping..."
fi

separator

#################### PARU INSTALL ####################

paru_packages_len=$(wc -l packages/paru.txt | awk '{print $1}')
logging_info "Installing [${paru_packages_len}] packages (this might take some time)..."
mapfile -t paru_packages < packages/paru.txt
if ! paru -S --needed --noconfirm "${paru_packages[@]}" > /dev/null 2>&1; then
	logging_error "Error occurred when installing [paru] packages! Cancelling..."
	exit 1
fi
logging_ok "Successfully installed [paru] packages"

separator

#################### ENABLE SERVICES ####################

logging_info "Enabling services..."
mapfile -t services < services.txt
if ! echo "$pass" | sudo -S systemctl enable --now "${services[@]}" > /dev/null 2>&1; then
	logging_warning "Error occurred while enabling service(s)! Cancelling..."
	exit 1
fi
logging_ok "Services enabled"

separator

#################### ENABLE VIRSH ####################

logging_info "Enabling the [virsh] network..."
echo "$pass" | sudo -S virsh net-start default
echo "$pass" | sudo -S virsh net-autostart default

#################### VSCODE ####################

# install extensions
logging_info "Installing [code-oss] extensions..."
path="configure/code-oss/extensions.txt"
if ! cat "${path}" | xargs -n 1 code --install-extension; then
	logging_warning "Error occurred while installing [code-oss] extension(s)! Cancelling..."
	exit 1
fi
logging_ok "Successfully installed [code-oss] extensions"

# link config
target_path="$HOME/.config/Code - OSS/User"
source_path="$(pwd)/configure/code-oss/User/settings.json"
check_create_dir "$target_path"
if ! ln -s -- "$source_path" "$target_path"; then
	logging_error "Failed to link [code] settings file! Cancelling..."
	exit 1
fi
logging_ok "Linked [code] settings file"

separator

#################### ADD USER TO LIBVIRT GROUP ####################

# For permission to start up kvm/qemu.
logging_info "Adding [${USER}] to [libvirt] group..."
if ! echo "$pass" | sudo -S usermod -aG libvirt $USER; then
	logging_error "Unable to add user to group! Cancelling..."
	exit 1
fi
logging_ok "User added to group without issues"

separator

#################### SYMLINK KEYD CONFIG ####################

logging_info "Symlinking [keyd] config..."
path="$HOME/.config/keyd/default.conf"
target="/etc/keyd/"
if ! echo "$pass" | sudo -S ln -s -- "$path" "$target"; then
	logging_error "Error occurred while symlinking [keyd] config! Cancelling..."
	exit 1
fi
logging_ok "[keyd] config symlinked without isses"

separator

#################### SET THEME ####################

# Arch relies mostly on this, instead of only GTK / QT, and needs to be set.
gsettings set org.gnome.desktop.interface icon-theme "Papirus"

#################### END ####################

echo "Done!"
