#!/usr/bin/env bash

path="~/.config/nvim/parser"

#=========#
# Prepare #
#=========#

mkdir -p $path

#=======#
# Regex #
#=======#

git clone https://github.com/tree-sitter/tree-sitter-regex.git
cd tree-sitter-regex
tree-sitter build
mv regex.so $path

#======#
# Bash #
#======#

git clone https://github.com/tree-sitter/tree-sitter-bash.git
cd tree-sitter-bash
tree-sitter build
mv bash.so $path
