filetype on
syntax on
set cursorline
set expandtab
set number
set relativenumber
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smartindent
highlight CursorLine ctermbg=236 guibg=#303030 cterm=NONE gui=NONE
