set-option -g history-limit 50000
set-option -g display-time 4000
set-option -g focus-events on
set-option -g mouse on

unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

set-option -g mode-keys vi
set-option -g status-keys emacs

set-option -g base-index 1
set-option -g renumber-windows on

set-option -g status-position top
set-option -g status-justify absolute-centre
set-option -g status-style bg="#141414",fg=purple
set-option -g status-right "#[fg=red] [#H] #[fg=default][#S] "

set -g window-status-current-style "bg=purple,fg=black,bold"
set -g window-status-current-format " #I:#W "

set-option -g message-style bg=purple,fg=black
set-option -g prompt-cursor-colour black

bind-key C-p previous-window
bind-key C-n next-window
bind-key C-l last-window

bind-key R run-shell " \
    tmux source-file /home/gobbls/.config/tmux/tmux.conf > /dev/null; \
    tmux display-message 'Sourced /home/gobbls/.config/tmux/tmux.conf!'"
