return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"css",
			"gitignore",
			"html",
			"ini",
			"javascript",
			"json",
			"jsonc",
			"lua",
			"markdown",
			"markdown_inline",
			"python",
			"regex",
			"svelte",
			"tmux",
			"toml",
			"typescript",
			"vim",
			"vimdoc",
			"vue",
			"xml",
			"yaml",
		},
		auto_install = true,
		highlight = { enable = true },
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
