unbind C-b

set -g history-limit 50000
set -g display-time 4000
set -g allow-passthrough on
set -g focus-events on
set -g mode-keys vi
set -g status-keys emacs
set -g mouse on
set -g cursor-style blinking-block
set -g base-index 1
set -g renumber-windows on
set -g status-left-length 50
set -g prefix C-Space
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g status-left ""
set -g status-right "[#S] %H:%M %d-%b-%y"
set -g window-status-format "#[bold]#I:#W" 
set -g window-status-current-format "#[bold]#I:#W*" 
set -g window-status-last-style italics,dim

bind C-Space send-prefix
bind C-p previous-window
bind C-n next-window
bind C-l last-window

bind R run-shell " \
    tmux source-file /home/gobbls/.config/tmux/tmux.conf > /dev/null; \
    tmux display-message 'Sourced /home/gobbls/.config/tmux/tmux.conf!'"
