#############
# == QOL == #
#############

# Recomended by Neovim
set -g focus-events on
set -g default-terminal "tmux-256color"
set -a terminal-features 'ghostty:RGB'

# Fixing colors, as recomended here: \
# [Configure your Git](https://www.youtube.com/watch?v=wpODsyBHxH0)
set -sg terminal-overrides ",*:RGB"

#set -g pane-base-index 1
set -g mouse on
set -g mode-keys vi
set -s escape-time 0
set -g base-index 1
set -g renumber-windows on

##################
# == KEYBINDS == #
##################

unbind SPACE
set -g prefix C-SPACE

unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Vim motions(-like) pane splitting (using shift).
unbind %
bind J split-window -v
bind L split-window -h

# Vim motions pane selection.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

####################
# == STATUSLINE == #
####################

#set -g status 2
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=terminal, fg=terminal"
set -g status-left ""
set -g status-right "[#S]"

set -g window-status-current-style "fg=#b6927b bold"

#############
# == TPM == #
#############

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

##############
# == MISC == #
##############

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
